name: Timeout Check

on:
  push:
    branches:
      - "*"  # Or whichever branch you want this action to trigger on.

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run script with timeout
        id: timeout-step
        run: |
          chmod +x sleep_for_1_hour.sh
          ./sleep_for_1_hour.sh
        timeout-minutes: 2
        continue-on-error: true

      - name: Check for timeout
        run: |
          if [[ "${{ steps.timeout-step.outcome }}" == "failure" ]]; then
            echo "::set-output name=timedout::true"
          else
            echo "::set-output name=timedout::false"
          fi
        if: always()

      - name: Notify Slack on timeout
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit
          text: "The job timed out!"
        if: steps.check-timeout.outputs.timedout == 'true'  # Only run this step if timeout occurred
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}  # Set this in your GitHub repo secrets
 

